image:
  repository: nandanrao/agrius-claws
  tag: 0.0.1
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

schedule: "0 0 * * *"
queue: {}
google: {}
sheets: {}
resources: {}
redis: {}
tokens: {}
config: {}
